# Generated by Django 5.0.5 on 2024-05-07 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, help_text='Score obtained by the user in the quiz.')),
                ('total_questions', models.PositiveIntegerField(default=0, help_text='Total number of questions in the quiz.')),
                ('completed', models.BooleanField(default=False, help_text='Indicates if the user has completed the quiz.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(help_text='Quiz attempted by the user.', on_delete=django.db.models.deletion.CASCADE, related_name='user_attempts', to='quiz_app.quiz')),
                ('user', models.ForeignKey(help_text='User who attempted the quiz.', on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
