# Generated by Django 5.0.5 on 2024-05-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_userquizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_attempts',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of attempts allowed for the quiz.'),
        ),
    ]
