# Generated by Django 5.0.5 on 2024-05-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_quiz_max_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(help_text='Description of the quiz.'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(help_text='Title of the quiz.', max_length=255, unique=True),
        ),
    ]
